{
 "title": "Monitoring Stack",
 "panels": [
  {
   "title": "Total Targets Up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "count(up == 1)" }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "max(up{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "max(up{service_name=\"vcc_grafana\"})"
    }
   ]
  },
  {
   "title": "Traefik",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "max(up{service_name=\"vcc_traefik\"})"
    }
   ]
  },
  {
   "title": "Dex",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "max(up{service_name=\"vcc_dex\"})"
    }
   ]
  },
  {
   "title": "Forgejo",
   "type": "stat",
   "gridPos": { "x": 20, "y": 0, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "max(up{service_name=\"vcc_forgejo\"})"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "max(up{service_name=\"vcc_loki\"})"
    }
   ]
  },
  {
   "title": "Promtail",
   "type": "stat",
   "gridPos": { "x": 4, "y": 4, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "count(up{service_name=\"vcc_promtail\"} == 1)"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "stat",
   "gridPos": { "x": 8, "y": 4, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"} == 1)"
    }
   ]
  },
  {
   "title": "Registry",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 4, "h": 4 },
   "targets": [
    {
     "expr": "count(up{job=\"registry\"} == 1)"
    }
   ]
  }
 ]
}