[DEFAULT]
APP_NAME = VCC Git
RUN_MODE = prod

[server]
# TODO https
ROOT_URL = http://git.vcc.internal
DOMAIN = git.vcc.internal
HTTP_PORT = 3200

SSH_PORT = 2222
LFS_START_SERVER = true
# TODO maybe it should not be here
LFS_JWT_SECRET = supersupersecret

OFFLINE_MODE = true

[indexer]
REPO_INDEXER_ENABLED = true

[security]
INSTALL_LOCK = true
# TODO maybe it should not be here
SECRET_KEY = supersupersecret
COOKIE_USERNAME = vcc_git_username
COOKIE_REMEMBER_NAME = vcc_git_remember_me
# TODO maybe it should not be here
INTERNAL_TOKEN = supersupersecret

[database]
# TODO use postgres
DB_TYPE = sqlite3

# TODO something for sessions
# TODO something for queues
# TODO something for metrics
