networks:
  internal_net:
    driver: overlay

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ vault_postgres_password }}"
    networks:
      - internal_net
    volumes:
      - /data/postgres:/var/lib/postgresql/data
      - /data/configs/postgres/init:/docker-entrypoint-initdb.d:ro

  dex:
    image: ghcr.io/dexidp/dex:v2.41.1-alpine
    user: root
    networks:
      - internal_net
    volumes:
      - /data/dex:/data
      - /data/configs/dex/dex.yaml:/etc/dex/config.docker.yaml:ro
    command: ["dex", "serve", "/etc/dex/config.docker.yaml"]
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dex.rule=Host(`auth.{{ domain_name }}`)"
        - "traefik.http.routers.dex.entrypoints=websecure"
        - "traefik.http.routers.dex.tls=true"
        - "traefik.http.services.dex.loadbalancer.server.port=5556"

  traefik:
    # new Docker requires 1.44+, This prevented Traefik from discovering services via swarm provider (Dex unreachable)
    image: public.ecr.aws/docker/library/traefik:v3.6.2
    networks:
      internal_net:
        aliases:
          - auth.{{ domain_name }}
          - git.{{ domain_name }}
          - mon.{{ domain_name }}
          - prom.{{ domain_name }}
    command:
      - --accesslog=true
      - --accesslog.format=json
      - --log.level=INFO
      - --log.format=json
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=metrics
      - --providers.swarm=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedByDefault=false
      - --providers.swarm.network=vcc_internal_net
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --providers.file.filename=/etc/traefik/tls.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - {{ cert_dir }}:/etc/certs:ro
      - /data/configs/traefik/tls.yml:/etc/traefik/tls.yml:ro
    deploy:
      placement:
        constraints: ["node.role == manager"]
      labels:
        - "traefik.enable=false"
        - "prometheus.io/scrape-me=yes-please"
        - "prometheus.io/metrics-port=8082"
