---
- name: Copy docker-compose files to remote host
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/{{ item }}"
  loop: "{{ stack_file_names }}"

- name: Undeploy stack
  community.docker.docker_stack:
    state: absent
    name: vcc
    detach: false
  when: stack_recreate

- name: Install rsync
  ansible.builtin.apt:
    name:
      - rsync

- name: Delete directories in /data
  ansible.builtin.file:
    path: "/data/{{ item }}"
    state: absent
  loop: "{{ stack_data_directories }}"
  when: stack_nuke_data_directories

- name: Create directories in /data
  ansible.builtin.file:
    path: "/data/{{ item }}"
    state: directory
  loop: "{{ stack_data_directories }}"

- name: Create /data/configs
  ansible.builtin.file:
    path: /data/configs
    state: directory

- name: Copy configs
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/configs/"
    dest: "/data/configs/"
    archive: true
    delete: true

- name: Create postgres init directory
  ansible.builtin.file:
    path: /data/configs/postgres/init
    state: directory

- name: Copy postgres init script
  ansible.builtin.template:
    src: postgres/001-init.sql
    dest: /data/configs/postgres/init/001-init.sql

- name: Create dex config directory
  ansible.builtin.file:
    path: /data/configs/dex
    state: directory

- name: Copy dex config
  ansible.builtin.template:
    src: dex/dex.yaml
    dest: /data/configs/dex/dex.yaml

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: vcc
    prune: true
    detach: false
    with_registry_auth: true
    compose: "{{ ['/opt/'] | product(stack_file_names) | map('join') | list }}" # this is evil
  # retry the task that may fail
  retries: 3
  delay: 1
  register: result
  until: result is not failed
